<?php
/**
 * Fichier gérant le peuplement de la table spip_devises (+ spip_pays_liens)
 *
 * @plugin     Bigaille
 * @copyright  2015
 * @author     C.R
 * @licence    GNU/GPL
 */

if (!defined("_ECRIRE_INC_VERSION")) return;

/**
 * Peuplement de la base spip_devises.
 *
 * https://fr.wikipedia.org/wiki/ISO_4217
 * https://fr.wikipedia.org/wiki/Devise_%28monnaie%29
 *
 * Les codes des devises sont formés de trois lettres :
 * - Les deux premières lettres correspondent au code ISO 3166-1 alpha 2
 *   du pays émetteur de la monnaie (US > États-Unis, AU > Australie, etc.).
 * - La dernière lettre du code correspond en principe à l'initiale
 *   du nom de la devise (D pour dollar, etc.).
 *
 * @return void
**/
function peupler_base_devises() {

	// Devises
	$devises = array(
		array(
			'id_devise'    => 1,
			'devise'       => 'ADF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 2,
			'devise'       => 'ADP',
			'nom'          => '<multi>[fr]Peseta</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 3,
			'devise'       => 'AED',
			'nom'          => '<multi>[fr]Dirham</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 4,
			'devise'       => 'AFA',
			'nom'          => '<multi>[fr]Afghani</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 5,
			'devise'       => 'AFN',
			'nom'          => '<multi>[fr]Afghani</multi>',
			'complement'   => '<multi>[fr]nouvel</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 6,
			'devise'       => 'ALL',
			'nom'          => '<multi>[fr]Lek</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 7,
			'devise'       => 'AMD',
			'nom'          => '<multi>[fr]Dram</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 8,
			'devise'       => 'ANG',
			'nom'          => '<multi>[fr]Florin</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 9,
			'devise'       => 'AOA',
			'nom'          => '<multi>[fr]Kwanza</multi>',
			'complement'   => '<multi>[fr]ajusté (2000-)</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 10,
			'devise'       => 'AOK',
			'nom'          => '<multi>[fr]Kwanza</multi>',
			'complement'   => '<multi>[fr]ancien (1977-1990)</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 11,
			'devise'       => 'AON',
			'nom'          => '<multi>[fr]Kwanza</multi>',
			'complement'   => '<multi>[fr]nouveau (1990-2000)</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 12,
			'devise'       => 'AOR',
			'nom'          => '<multi>[fr]Kwanza</multi>',
			'complement'   => '<multi>[fr]réajusté (1995-1999)</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 13,
			'devise'       => 'ARP',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 14,
			'devise'       => 'ARS',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 15,
			'devise'       => 'ATS',
			'nom'          => '<multi>[fr]Schilling</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 16,
			'devise'       => 'AUD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 17,
			'devise'       => 'AWG',
			'nom'          => '<multi>[fr]Florin</multi>',
			'complement'   => '',
			'symbole'      => '&fnof;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 18,
			'devise'       => 'AZM',
			'nom'          => '<multi>[fr]Manat</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 19,
			'devise'       => 'AZN',
			'nom'          => '<multi>[fr]Manat</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 20,
			'devise'       => 'BAM',
			'nom'          => '<multi>[fr]Mark convertible</multi>',
			'complement'   => '<multi>[fr]marka</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 21,
			'devise'       => 'BBD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 22,
			'devise'       => 'BDT',
			'nom'          => '<multi>[fr]Taka</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 23,
			'devise'       => 'BEF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 24,
			'devise'       => 'BGJ',
			'nom'          => '<multi>[fr]Lev</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 25,
			'devise'       => 'BGK',
			'nom'          => '<multi>[fr]Lev</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 26,
			'devise'       => 'BGL',
			'nom'          => '<multi>[fr]Lev</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 27,
			'devise'       => 'BGN',
			'nom'          => '<multi>[fr]Lev</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 28,
			'devise'       => 'BHD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 29,
			'devise'       => 'BIF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 30,
			'devise'       => 'BMD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 31,
			'devise'       => 'BND',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 32,
			'devise'       => 'BOB',
			'nom'          => '<multi>[fr]Boliviano</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 33,
			'devise'       => 'BOP',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 34,
			'devise'       => 'BOV',
			'nom'          => '<multi>[fr]Mvdol</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 35,
			'devise'       => 'BRL',
			'nom'          => '<multi>[fr]Réal</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 36,
			'devise'       => 'BRR',
			'nom'          => '<multi>[fr]Réal</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 37,
			'devise'       => 'BSD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 38,
			'devise'       => 'BTN',
			'nom'          => '<multi>[fr]Ngultrum</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 39,
			'devise'       => 'BWP',
			'nom'          => '<multi>[fr]Pula</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 40,
			'devise'       => 'BYR',
			'nom'          => '<multi>[fr]Rouble</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 41,
			'devise'       => 'BZD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 42,
			'devise'       => 'CAD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 43,
			'devise'       => 'CDF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 44,
			'devise'       => 'CHE',
			'nom'          => '<multi>[fr]Euro WIR</multi>',
			'complement'   => '',
			'symbole'      => '&euro;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 45,
			'devise'       => 'CHF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 46,
			'devise'       => 'CHW',
			'nom'          => '<multi>[fr]Franc WIR</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 47,
			'devise'       => 'CLF',
			'nom'          => '<multi>[fr]Unité d\'investissement</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 48,
			'devise'       => 'CLP',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 49,
			'devise'       => 'CNY',
			'nom'          => '<multi>[fr]Yuan renminbi</multi>',
			'complement'   => '',
			'symbole'      => '&yen;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 50,
			'devise'       => 'COP',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 51,
			'devise'       => 'COU',
			'nom'          => '<multi>[fr]Unité de valeur Réelle</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 52,
			'devise'       => 'CRC',
			'nom'          => '<multi>[fr]Colon</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 53,
			'devise'       => 'CSD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 54,
			'devise'       => 'CSK',
			'nom'          => '<multi>[fr]Couronne</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 55,
			'devise'       => 'CUC',
			'nom'          => '<multi>[fr]Peso convertible</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 56,
			'devise'       => 'CUP',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 57,
			'devise'       => 'CVE',
			'nom'          => '<multi>[fr]Escudo</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 58,
			'devise'       => 'CYP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'satut'        => 'obsolete',
		),
		array(
			'id_devise'    => 59,
			'devise'       => 'CZK',
			'nom'          => '<multi>[fr]Couronne</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 60,
			'devise'       => 'DEM',
			'nom'          => '<multi>[fr]Mark</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 61,
			'devise'       => 'DJF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 62,
			'devise'       => 'DKK',
			'nom'          => '<multi>[fr]Couronne</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 63,
			'devise'       => 'DOP',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 64,
			'devise'       => 'DZD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 65,
			'devise'       => 'ECS',
			'nom'          => '<multi>[fr]Sucre</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 66,
			'devise'       => 'ECV',
			'nom'          => '<multi>[fr]Unité de valeur constante</multi>',
			'complement'   => '<multi>[fr]UCV</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 67,
			'devise'       => 'EEK',
			'nom'          => '<multi>[fr]Couronne</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 68,
			'devise'       => 'EGP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 69,
			'devise'       => 'ERN',
			'nom'          => '<multi>[fr]Nafka</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 70,
			'devise'       => 'ESP',
			'nom'          => '<multi>[fr]Peseta</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 71,
			'devise'       => 'ETB',
			'nom'          => '<multi>[fr]Birr</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 72,
			'devise'       => 'EUR',
			'nom'          => '<multi>[fr]Euro</multi>',
			'complement'   => '',
			'symbole'      => '&euro;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 73,
			'devise'       => 'FIM',
			'nom'          => '<multi>[fr]Markka</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 74,
			'devise'       => 'FJD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 75,
			'devise'       => 'FKP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 76,
			'devise'       => 'FRF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 77,
			'devise'       => 'GBP',
			'nom'          => '<multi>[fr]Livre sterling</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 78,
			'devise'       => 'GEL',
			'nom'          => '<multi>[fr]Lari</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 79,
			'devise'       => 'GHS',
			'nom'          => '<multi>[fr]Cedi</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 80,
			'devise'       => 'GIP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 81,
			'devise'       => 'GMD',
			'nom'          => '<multi>[fr]Dalasi</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 82,
			'devise'       => 'GNF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 83,
			'devise'       => 'GRD',
			'nom'          => '<multi>[fr]Drachme</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 84,
			'devise'       => 'GTQ',
			'nom'          => '<multi>[fr]Quetzal</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 85,
			'devise'       => 'GWP',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 86,
			'devise'       => 'GYD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 87,
			'devise'       => 'HKD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 88,
			'devise'       => 'HNL',
			'nom'          => '<multi>[fr]Lempira</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 89,
			'devise'       => 'HRK',
			'nom'          => '<multi>[fr]Kuna</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 90,
			'devise'       => 'HTG',
			'nom'          => '<multi>[fr]Gourde</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 91,
			'devise'       => 'HUF',
			'nom'          => '<multi>[fr]Forint</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 92,
			'devise'       => 'IDR',
			'nom'          => '<multi>[fr]Roupie</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 93,
			'devise'       => 'IEP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 94,
			'devise'       => 'ILS',
			'nom'          => '<multi>[fr]Shekel</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 95,
			'devise'       => 'INR',
			'nom'          => '<multi>[fr]Roupie</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 96,
			'devise'       => 'IQD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 97,
			'devise'       => 'IRR',
			'nom'          => '<multi>[fr]Rial</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 98,
			'devise'       => 'ISK',
			'nom'          => '<multi>[fr]Couronne</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 99,
			'devise'       => 'ITL',
			'nom'          => '<multi>[fr]Lire</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 100,
			'devise'       => 'JMD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 101,
			'devise'       => 'JOD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 102,
			'devise'       => 'JPY',
			'nom'          => '<multi>[fr]Yen</multi>',
			'complement'   => '',
			'symbole'      => '&yen;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 103,
			'devise'       => 'KES',
			'nom'          => '<multi>[fr]Shilling</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 104,
			'devise'       => 'KGS',
			'nom'          => '<multi>[fr]Som</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 105,
			'devise'       => 'KHR',
			'nom'          => '<multi>[fr]Riel</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 106,
			'devise'       => 'KMF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 107,
			'devise'       => 'KPW',
			'nom'          => '<multi>[fr]Won</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 108,
			'devise'       => 'KRW',
			'nom'          => '<multi>[fr]Won</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 109,
			'devise'       => 'KWD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 110,
			'devise'       => 'KYD',
			'nom'          => '<multi>[fr]Dolar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 111,
			'devise'       => 'KZT',
			'nom'          => '<multi>[fr]Tenge</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 112,
			'devise'       => 'LAK',
			'nom'          => '<multi>[fr]Kip</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 113,
			'devise'       => 'LBP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 114,
			'devise'       => 'LKR',
			'nom'          => '<multi>[fr]Roupie</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 115,
			'devise'       => 'LRD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 116,
			'devise'       => 'LSL',
			'nom'          => '<multi>[fr]Loti</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 117,
			'devise'       => 'LTL',
			'nom'          => '<multi>[fr]Litas</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 118,
			'devise'       => 'LUF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 119,
			'devise'       => 'LVL',
			'nom'          => '<multi>[fr]Lats</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 120,
			'devise'       => 'LVR',
			'nom'          => '<multi>[fr]Rouble</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 121,
			'devise'       => 'LYD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 122,
			'devise'       => 'MAD',
			'nom'          => '<multi>[fr]Dirham</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 123,
			'devise'       => 'MDL',
			'nom'          => '<multi>[fr]Leu</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 124,
			'devise'       => 'MGA',
			'nom'          => '<multi>[fr]Ariary</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 125,
			'devise'       => 'MGF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 126,
			'devise'       => 'MKD',
			'nom'          => '<multi>[fr]Denar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 127,
			'devise'       => 'MMK',
			'nom'          => '<multi>[fr]Kyat</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 128,
			'devise'       => 'MNT',
			'nom'          => '<multi>[fr]Tugrik</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 129,
			'devise'       => 'MOP',
			'nom'          => '<multi>[fr]Pataca</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 130,
			'devise'       => 'MRO',
			'nom'          => '<multi>[fr]Ouguiya</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 131,
			'devise'       => 'MTL',
			'nom'          => '<multi>[fr]Lire</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 132,
			'devise'       => 'MUR',
			'nom'          => '<multi>[fr]Roupie</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 133,
			'devise'       => 'MVR',
			'nom'          => '<multi>[fr]Rufiyaa</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 134,
			'devise'       => 'MWK',
			'nom'          => '<multi>[fr]Kwacha</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 135,
			'devise'       => 'MXN',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 136,
			'devise'       => 'MXV',
			'nom'          => '<multi>[fr]Unité de conversion</multi>',
			'complement'   => '<multi>[fr]UDI</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 137,
			'devise'       => 'MYR',
			'nom'          => '<multi>[fr]Ringgit</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 138,
			'devise'       => 'MZE',
			'nom'          => '<multi>[fr]Escudo</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 139,
			'devise'       => 'MZM',
			'nom'          => '<multi>[fr]Metical</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 140,
			'devise'       => 'MZN',
			'nom'          => '<multi>[fr]Metical</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 141,
			'devise'       => 'NAD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 142,
			'devise'       => 'NGN',
			'nom'          => '<multi>[fr]Naira</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 143,
			'devise'       => 'NHF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 144,
			'devise'       => 'NIC',
			'nom'          => '<multi>[fr]Cordoba</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 145,
			'devise'       => 'NIO',
			'nom'          => '<multi>[fr]Cordoba d\'or</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 146,
			'devise'       => 'NLG',
			'nom'          => '<multi>[fr]Florin</multi>',
			'complement'   => '',
			'symbole'      => '&fnof;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 147,
			'devise'       => 'NOK',
			'nom'          => '<multi>[fr]Couronne</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 148,
			'devise'       => 'NPR',
			'nom'          => '<multi>[fr]Roupie</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 149,
			'devise'       => 'NZD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 150,
			'devise'       => 'OMR',
			'nom'          => '<multi>[fr]Rial</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 151,
			'devise'       => 'PAB',
			'nom'          => '<multi>[fr]Balboa</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 152,
			'devise'       => 'PEN',
			'nom'          => '<multi>[fr]Sol</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 153,
			'devise'       => 'PES',
			'nom'          => '<multi>[fr]Sol</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 154,
			'devise'       => 'PGK',
			'nom'          => '<multi>[fr]Kina</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 155,
			'devise'       => 'PHP',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 156,
			'devise'       => 'PKR',
			'nom'          => '<multi>[fr]Roupie</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 157,
			'devise'       => 'PLN',
			'nom'          => '<multi>[fr]Zloty</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 158,
			'devise'       => 'PLZ',
			'nom'          => '<multi>[fr]Zloty</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 159,
			'devise'       => 'PTE',
			'nom'          => '<multi>[fr]Escudo</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 160,
			'devise'       => 'PYG',
			'nom'          => '<multi>[fr]Guarani</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 161,
			'devise'       => 'QAR',
			'nom'          => '<multi>[fr]Rial</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 162,
			'devise'       => 'ROL',
			'nom'          => '<multi>[fr]Leu</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 163,
			'devise'       => 'RON',
			'nom'          => '<multi>[fr]Leu</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 164,
			'devise'       => 'RSD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 165,
			'devise'       => 'RUB',
			'nom'          => '<multi>[fr]Rouble russe</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 166,
			'devise'       => 'RWF',
			'nom'          => '<multi>[fr]Franc</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 167,
			'devise'       => 'SAR',
			'nom'          => '<multi>[fr]Riyal</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 168,
			'devise'       => 'SBD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 169,
			'devise'       => 'SCR',
			'nom'          => '<multi>[fr]Roupie</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 170,
			'devise'       => 'SDD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 171,
			'devise'       => 'SDG',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '<multi>[fr]nouvelle</multi>',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 172,
			'devise'       => 'SDP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '<multi>[fr]ancienne</multi>',
			'symbole'      => '&pound;',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 173,
			'devise'       => 'SEK',
			'nom'          => '<multi>[fr]Couronne</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 174,
			'devise'       => 'SGD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 175,
			'devise'       => 'SHP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 176,
			'devise'       => 'SIT',
			'nom'          => '<multi>[fr]Tolar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 177,
			'devise'       => 'SKK',
			'nom'          => '<multi>[fr]Couronne</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 178,
			'devise'       => 'SLL',
			'nom'          => '<multi>[fr]Leone</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 179,
			'devise'       => 'SML',
			'nom'          => '<multi>[fr]Lire</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 180,
			'devise'       => 'SOS',
			'nom'          => '<multi>[fr]Shilling</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 181,
			'devise'       => 'SRD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 182,
			'devise'       => 'SSP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 183,
			'devise'       => 'STD',
			'nom'          => '<multi>[fr]Dobra</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 184,
			'devise'       => 'SUB',
			'nom'          => '<multi>[fr]Rouble soviétique</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 185,
			'devise'       => 'SUR',
			'nom'          => '<multi>[fr]Rouble</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 186,
			'devise'       => 'SVC',
			'nom'          => '<multi>[fr]Colon</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 187,
			'devise'       => 'SYP',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 188,
			'devise'       => 'SZL',
			'nom'          => '<multi>[fr]Lilangeni</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 189,
			'devise'       => 'THB',
			'nom'          => '<multi>[fr]Baht</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 190,
			'devise'       => 'TJS',
			'nom'          => '<multi>[fr]Somoni</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 191,
			'devise'       => 'TMM',
			'nom'          => '<multi>[fr]Manat</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 192,
			'devise'       => 'TMT',
			'nom'          => '<multi>[fr]Manat</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 193,
			'devise'       => 'TND',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 194,
			'devise'       => 'TOP',
			'nom'          => '<multi>[fr]Pa\'anga</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 195,
			'devise'       => 'TPE',
			'nom'          => '<multi>[fr]Escudo</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 196,
			'devise'       => 'TRL',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '<multi>[fr]ancienne</multi>',
			'symbole'      => '&pound;',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 197,
			'devise'       => 'TRY',
			'nom'          => '<multi>[fr]Livre</multi>',
			'complement'   => '',
			'symbole'      => '&pound;',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 198,
			'devise'       => 'TTD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 199,
			'devise'       => 'TWD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 200,
			'devise'       => 'TZS',
			'nom'          => '<multi>[fr]Shilling</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 201,
			'devise'       => 'UAH',
			'nom'          => '<multi>[fr]Hryvnia</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 202,
			'devise'       => 'UGX',
			'nom'          => '<multi>[fr]Shilling</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 203,
			'devise'       => 'USD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 204,
			'devise'       => 'USN',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '<multi>[fr]lendemain</multi>',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 205,
			'devise'       => 'USS',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '<multi>[fr]même jour</multi>',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 206,
			'devise'       => 'UYI',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '<multi>[fr]unité de compte</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 207,
			'devise'       => 'UYU',
			'nom'          => '<multi>[fr]Peso</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 208,
			'devise'       => 'UZS',
			'nom'          => '<multi>[fr]Sum</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 209,
			'devise'       => 'VAL',
			'nom'          => '<multi>[fr]Lire</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 210,
			'devise'       => 'VEB',
			'nom'          => '<multi>[fr]Bolivar</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 211,
			'devise'       => 'VEF',
			'nom'          => '<multi>[fr]Bolívar fuerté</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 212,
			'devise'       => 'VND',
			'nom'          => '<multi>[fr]Dong</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 213,
			'devise'       => 'VUV',
			'nom'          => '<multi>[fr]Vatu</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 214,
			'devise'       => 'WST',
			'nom'          => '<multi>[fr]Tala</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 215,
			'devise'       => 'XAF',
			'nom'          => '<multi>[fr]Franc CFA</multi>',
			'complement'   => '<multi>[fr]BEAC</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 216,
			'devise'       => 'XAG',
			'nom'          => '<multi>[fr]Argent</multi>',
			'complement'   => '<multi>[fr]libellé en onces</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 217,
			'devise'       => 'XAU',
			'nom'          => '<multi>[fr]Or</multi>',
			'complement'   => '<multi>[fr]libellé en onces</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 218,
			'devise'       => 'XBA',
			'nom'          => '<multi>[fr]Unité européenne composée</multi>',
			'complement'   => '<multi>[fr]EURCO</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 219,
			'devise'       => 'XBB',
			'nom'          => '<multi>[fr]Unité monétaire européenne</multi>',
			'complement'   => '<multi>[fr]U.M.E.-6</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 220,
			'devise'       => 'XBC',
			'nom'          => '<multi>[fr]Unité de compte 9</multi>',
			'complement'   => '<multi>[fr]U.E.C.-9</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 221,
			'devise'       => 'XBD',
			'nom'          => '<multi>[fr]Unité de compte 17</multi>',
			'complement'   => '<multi>[fr]U.E.C.-17</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 222,
			'devise'       => 'XCD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 223,
			'devise'       => 'XDR',
			'nom'          => '<multi>[fr]Droits de tirages spéciaux</multi>',
			'complement'   => '<multi>[fr]DTS</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 224,
			'devise'       => 'XEU',
			'nom'          => '<multi>[fr]Unité de compte européen</multi>',
			'complement'   => '<multi>[fr]ECU</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 225,
			'devise'       => 'XFO',
			'nom'          => '<multi>[fr]Franc or</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 226,
			'devise'       => 'XFU',
			'nom'          => '<multi>[fr]Franc UIC</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 227,
			'devise'       => 'XOF',
			'nom'          => '<multi>[fr]Franc CFA</multi>',
			'complement'   => '<multi>[fr]BCEAO</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 228,
			'devise'       => 'XPD',
			'nom'          => '<multi>[fr]Palladium</multi>',
			'complement'   => '<multi>[fr]libellé en onces</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 229,
			'devise'       => 'XPF',
			'nom'          => '<multi>[fr]Franc CFP</multi>',
			'complement'   => '<multi>[fr]IEOM</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 230,
			'devise'       => 'XPT',
			'nom'          => '<multi>[fr]Platine</multi>',
			'complement'   => '<multi>[fr]libbelé en onces</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 231,
			'devise'       => 'YER',
			'nom'          => '<multi>[fr]Rial</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 232,
			'devise'       => 'YUD',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '<multi>[fr]3e, dit « dinar fort »</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 233,
			'devise'       => 'YUF',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '<multi>[fr]2e, dit « dinar de la Fédération »</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 234,
			'devise'       => 'YUG',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '<multi>[fr]7e, dit « dinar de 1994 »</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 235,
			'devise'       => 'YUM',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '<multi>[fr]8e, dit « novi dinar »</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 236,
			'devise'       => 'YUN',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '<multi>[fr]4e, dit « dinar convertible»</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 237,
			'devise'       => 'YUO',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '<multi>[fr]6e, dit « dinar de 1993 »</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 238,
			'devise'       => 'YUR',
			'nom'          => '<multi>[fr]Dinar</multi>',
			'complement'   => '<multi>[fr]5e, dit « dinar réformé »</multi>',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 239,
			'devise'       => 'ZAR',
			'nom'          => '<multi>[fr]Rand</multi>',
			'complement'   => '<multi>[fr]compte convertible</multi>',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 240,
			'devise'       => 'ZMK',
			'nom'          => '<multi>[fr]Kwacha</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 241,
			'devise'       => 'ZMW',
			'nom'          => '<multi>[fr]Kwacha</multi>',
			'complement'   => '',
			'symbole'      => '',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 242,
			'devise'       => 'ZWD',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '$',
			'statut'       => 'obsolete',
		),
		array(
			'id_devise'    => 243,
			'devise'       => 'ZWL',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '<multi>[fr]nouveau</multi>',
			'symbole'      => '$',
			'statut'       => 'actuelle',
		),
		array(
			'id_devise'    => 244,
			'devise'       => 'ZWR',
			'nom'          => '<multi>[fr]Dollar</multi>',
			'complement'   => '<multi>[fr]ancien</multi>',
			'symbole'      => '$',
			'statut'       => 'obsolete',
		)
	);

	// Pays
	$pays_liens = array(
		array(
			'objet'    => 'devise',
			'id_objet' => 1,
			'id_pays'  => 7,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 3,
			'id_pays'  => 61,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 4,
			'id_pays'  => 1,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 5,
			'id_pays'  => 1,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 6,
			'id_pays'  => 4,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 7,
			'id_pays'  => 15,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 8,
			'id_pays'  => 16,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 8,
			'id_pays'  => 12,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 8,
			'id_pays'  => 247,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 8,
			'id_pays'  => 250,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 9,
			'id_pays'  => 8,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 10,
			'id_pays'  => 8,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 11,
			'id_pays'  => 8,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 12,
			'id_pays'  => 8,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 13,
			'id_pays'  => 14,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 14,
			'id_pays'  => 14,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 15,
			'id_pays'  => 18,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 16,
			'id_pays'  => 94,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 16,
			'id_pays'  => 97,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 16,
			'id_pays'  => 122,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 16,
			'id_pays'  => 156,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 16,
			'id_pays'  => 17,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 16,
			'id_pays'  => 162,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 16,
			'id_pays'  => 248,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 16,
			'id_pays'  => 234,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 17,
			'id_pays'  => 16,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 18,
			'id_pays'  => 19,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 19,
			'id_pays'  => 19,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 20,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 21,
			'id_pays'  => 23,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 22,
			'id_pays'  => 22,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 23,
			'id_pays'  => 24,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 24,
			'id_pays'  => 36,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 25,
			'id_pays'  => 36,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 26,
			'id_pays'  => 36,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 27,
			'id_pays'  => 36,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 28,
			'id_pays'  => 21,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 29,
			'id_pays'  => 38,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 30,
			'id_pays'  => 27,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 31,
			'id_pays'  => 35,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 32,
			'id_pays'  => 31,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 33,
			'id_pays'  => 31,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 34,
			'id_pays'  => 31,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 35,
			'id_pays'  => 34,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 36,
			'id_pays'  => 34,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 37,
			'id_pays'  => 20,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 38,
			'id_pays'  => 28,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 39,
			'id_pays'  => 33,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 40,
			'id_pays'  => 29,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 41,
			'id_pays'  => 25,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 42,
			'id_pays'  => 41,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 43,
			'id_pays'  => 50,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 44,
			'id_pays'  => 213,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 45,
			'id_pays'  => 130,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 45,
			'id_pays'  => 213,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 46,
			'id_pays'  => 213,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 47,
			'id_pays'  => 44,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 48,
			'id_pays'  => 44,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 49,
			'id_pays'  => 45,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 50,
			'id_pays'  => 47,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 51,
			'id_pays'  => 47,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 52,
			'id_pays'  => 53,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 53,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 53,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 54,
			'id_pays'  => 207,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 54,
			'id_pays'  => 185,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 55,
			'id_pays'  => 56,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 56,
			'id_pays'  => 56,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 57,
			'id_pays'  => 42,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 58,
			'id_pays'  => 46,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 59,
			'id_pays'  => 185,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 60,
			'id_pays'  => 6,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 60,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 61,
			'id_pays'  => 58,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 62,
			'id_pays'  => 99,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 62,
			'id_pays'  => 57,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 62,
			'id_pays'  => 79,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 63,
			'id_pays'  => 184,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 64,
			'id_pays'  => 5,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 65,
			'id_pays'  => 62,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 66,
			'id_pays'  => 62,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 67,
			'id_pays'  => 65,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 68,
			'id_pays'  => 60,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 69,
			'id_pays'  => 63,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 70,
			'id_pays'  => 64,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 71,
			'id_pays'  => 67,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 80,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 182,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 77,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 186,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 114,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 175,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 150,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 245,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 88,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 146,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 143,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 140,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 132,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 131,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 126,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 195,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 196,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 6,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 7,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 18,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 24,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 46,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 238,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 3,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 64,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 65,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 69,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 70,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 222,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 207,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 72,
			'id_pays'  => 111,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 73,
			'id_pays'  => 69,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 74,
			'id_pays'  => 68,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 75,
			'id_pays'  => 100,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 75,
			'id_pays'  => 74,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 186,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 180,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 143,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 196,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 88,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 80,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 70,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 222,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 76,
			'id_pays'  => 146,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 77,
			'id_pays'  => 188,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 78,
			'id_pays'  => 73,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 79,
			'id_pays'  => 75,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 80,
			'id_pays'  => 76,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 81,
			'id_pays'  => 72,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 82,
			'id_pays'  => 84,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 83,
			'id_pays'  => 77,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 84,
			'id_pays'  => 82,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 85,
			'id_pays'  => 86,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 86,
			'id_pays'  => 87,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 87,
			'id_pays'  => 91,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 88,
			'id_pays'  => 90,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 89,
			'id_pays'  => 55,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 90,
			'id_pays'  => 89,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 91,
			'id_pays'  => 92,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 92,
			'id_pays'  => 108,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 93,
			'id_pays'  => 111,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 94,
			'id_pays'  => 113,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 94,
			'id_pays'  => 171,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 95,
			'id_pays'  => 107,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 96,
			'id_pays'  => 109,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 97,
			'id_pays'  => 110,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 98,
			'id_pays'  => 112,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 99,
			'id_pays'  => 114,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 100,
			'id_pays'  => 115,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 101,
			'id_pays'  => 118,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 102,
			'id_pays'  => 116,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 103,
			'id_pays'  => 120,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 104,
			'id_pays'  => 121,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 105,
			'id_pays'  => 39,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 106,
			'id_pays'  => 48,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 107,
			'id_pays'  => 51,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 108,
			'id_pays'  => 52,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 109,
			'id_pays'  => 123,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 110,
			'id_pays'  => 96,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 111,
			'id_pays'  => 119,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 112,
			'id_pays'  => 124,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 113,
			'id_pays'  => 127,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 114,
			'id_pays'  => 211,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 115,
			'id_pays'  => 128,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 116,
			'id_pays'  => 125,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 117,
			'id_pays'  => 131,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 118,
			'id_pays'  => 132,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 119,
			'id_pays'  => 126,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 120,
			'id_pays'  => 126,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 121,
			'id_pays'  => 129,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 122,
			'id_pays'  => 141,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 123,
			'id_pays'  => 149,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 124,
			'id_pays'  => 135,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 125,
			'id_pays'  => 135,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 126,
			'id_pays'  => 134,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 127,
			'id_pays'  => 30,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 128,
			'id_pays'  => 151,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 129,
			'id_pays'  => 133,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 130,
			'id_pays'  => 145,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 131,
			'id_pays'  => 140,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 132,
			'id_pays'  => 144,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 133,
			'id_pays'  => 138,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 134,
			'id_pays'  => 137,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 135,
			'id_pays'  => 147,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 136,
			'id_pays'  => 147,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 137,
			'id_pays'  => 136,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 138,
			'id_pays'  => 154,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 139,
			'id_pays'  => 154,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 140,
			'id_pays'  => 154,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 141,
			'id_pays'  => 155,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 142,
			'id_pays'  => 160,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 143,
			'id_pays'  => 237,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 144,
			'id_pays'  => 158,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 145,
			'id_pays'  => 158,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 146,
			'id_pays'  => 175,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 147,
			'id_pays'  => 215,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 147,
			'id_pays'  => 163,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 147,
			'id_pays'  => 93,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 148,
			'id_pays'  => 157,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 149,
			'id_pays'  => 178,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 149,
			'id_pays'  => 98,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 149,
			'id_pays'  => 161,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 149,
			'id_pays'  => 228,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 149,
			'id_pays'  => 165,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 150,
			'id_pays'  => 166,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 151,
			'id_pays'  => 172,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 152,
			'id_pays'  => 176,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 153,
			'id_pays'  => 176,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 154,
			'id_pays'  => 173,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 155,
			'id_pays'  => 177,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 156,
			'id_pays'  => 169,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 157,
			'id_pays'  => 179,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 158,
			'id_pays'  => 179,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 159,
			'id_pays'  => 182,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 159,
			'id_pays'  => 226,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 160,
			'id_pays'  => 174,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 161,
			'id_pays'  => 183,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 162,
			'id_pays'  => 187,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 163,
			'id_pays'  => 187,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 164,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 165,
			'id_pays'  => 189,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 166,
			'id_pays'  => 190,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 167,
			'id_pays'  => 13,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 168,
			'id_pays'  => 103,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 169,
			'id_pays'  => 204,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 170,
			'id_pays'  => 210,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 173,
			'id_pays'  => 212,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 174,
			'id_pays'  => 206,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 175,
			'id_pays'  => 193,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 176,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 177,
			'id_pays'  => 207,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 178,
			'id_pays'  => 205,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 179,
			'id_pays'  => 195,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 180,
			'id_pays'  => 209,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 181,
			'id_pays'  => 214,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 182,
			'id_pays'  => 249,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 183,
			'id_pays'  => 201,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 15,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 232,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 235,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 218,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 19,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 29,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 73,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 189,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 119,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 184,
			'id_pays'  => 168,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 185,
			'id_pays'  => 65,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 185,
			'id_pays'  => 131,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 185,
			'id_pays'  => 126,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 186,
			'id_pays'  => 198,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 187,
			'id_pays'  => 217,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 188,
			'id_pays'  => 216,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 189,
			'id_pays'  => 225,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 190,
			'id_pays'  => 218,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 191,
			'id_pays'  => 232,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 192,
			'id_pays'  => 232,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 193,
			'id_pays'  => 231,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 194,
			'id_pays'  => 229,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 195,
			'id_pays'  => 226,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 196,
			'id_pays'  => 233,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 197,
			'id_pays'  => 233,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 198,
			'id_pays'  => 230,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 199,
			'id_pays'  => 219,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 200,
			'id_pays'  => 220,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 201,
			'id_pays'  => 235,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 202,
			'id_pays'  => 167,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 62,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 66,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 82,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 89,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 101,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 102,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 104,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 105,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 106,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 142,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 148,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 170,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 172,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 181,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 198,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 200,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 223,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 203,
			'id_pays'  => 226,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 204,
			'id_pays'  => 66,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 205,
			'id_pays'  => 66,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 206,
			'id_pays'  => 236,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 207,
			'id_pays'  => 236,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 208,
			'id_pays'  => 168,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 209,
			'id_pays'  => 238,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 210,
			'id_pays'  => 239,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 211,
			'id_pays'  => 239,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 212,
			'id_pays'  => 240,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 213,
			'id_pays'  => 237,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 214,
			'id_pays'  => 199,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 215,
			'id_pays'  => 40,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 215,
			'id_pays'  => 43,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 215,
			'id_pays'  => 50,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 215,
			'id_pays'  => 71,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 215,
			'id_pays'  => 85,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 215,
			'id_pays'  => 221,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 222,
			'id_pays'  => 9,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 222,
			'id_pays'  => 11,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 222,
			'id_pays'  => 59,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 222,
			'id_pays'  => 78,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 222,
			'id_pays'  => 153,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 222,
			'id_pays'  => 192,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 222,
			'id_pays'  => 194,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 222,
			'id_pays'  => 197,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 227,
			'id_pays'  => 26,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 227,
			'id_pays'  => 37,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 227,
			'id_pays'  => 54,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 227,
			'id_pays'  => 86,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 227,
			'id_pays'  => 139,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 227,
			'id_pays'  => 159,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 227,
			'id_pays'  => 202,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 227,
			'id_pays'  => 227,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 229,
			'id_pays'  => 164,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 229,
			'id_pays'  => 180,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 229,
			'id_pays'  => 241,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 231,
			'id_pays'  => 242,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 232,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 232,
			'id_pays'  => 55,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 232,
			'id_pays'  => 134,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 232,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 232,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 232,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 233,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 233,
			'id_pays'  => 55,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 233,
			'id_pays'  => 134,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 233,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 233,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 233,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 234,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 234,
			'id_pays'  => 55,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 234,
			'id_pays'  => 134,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 234,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 234,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 234,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 235,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 235,
			'id_pays'  => 55,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 235,
			'id_pays'  => 134,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 235,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 235,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 235,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 236,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 236,
			'id_pays'  => 55,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 236,
			'id_pays'  => 134,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 236,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 236,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 236,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 237,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 237,
			'id_pays'  => 55,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 237,
			'id_pays'  => 134,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 237,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 237,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 237,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 238,
			'id_pays'  => 32,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 238,
			'id_pays'  => 55,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 238,
			'id_pays'  => 134,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 238,
			'id_pays'  => 152,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 238,
			'id_pays'  => 203,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 238,
			'id_pays'  => 208,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 239,
			'id_pays'  => 2,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 239,
			'id_pays'  => 155,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 241,
			'id_pays'  => 243,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 242,
			'id_pays'  => 243,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 243,
			'id_pays'  => 244,
		),
		array(
			'objet'    => 'devise',
			'id_objet' => 244,
			'id_pays'  => 244,
		),
	);

	// insertion des devises
	sql_insertq_multi('spip_devises', $devises);

	// insertion des pays
	sql_insertq_multi('spip_pays_liens', $pays_liens);

}
?>
